### ISSUE TITLE
[Feature] moti 프로젝트를 생성한다.

### ISSUE THREAD

**Issue by lsh23** [boostcampwm2023/iOS02-moti#1]
## issue
- 초기 Nest.js 프로젝트 셋업

## todo
- [x] Nest.js 프로젝트 생성
- [x] TypeORM 의존성 세팅
- [x] dotenv 의존성 세팅

**Comment by Dltmd202** [comment]
nest 프로젝트 생성

```jsx
nest new BE
```

typeorm 설정 및 db 연결

```jsx
npm install --save @nestjs/typeorm typeorm mysql2
```

AppModule 및 .env 파일 관리

```jsx
@Module({
  imports: [
    ConfigModule.forRoot(configServiceModuleOptions),
    TypeOrmModule.forRootAsync(typeOrmModuleOptions),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

.*.env

```jsx
DB=mysql
DB_HOST=127.0.0.1
DB_PORT=13306
DB_USERNAME=sehyeong
DB_PASSWORD=
DB_DATABASE=typeorm_test
```
