### ISSUE TITLE
[Feature] 자동 로그인에 따라 화면을 이동한다.

### ISSUE THREAD

**Issue by jeongju9216** [boostcampwm2023/iOS02-moti#113]
## issue
- 자동 로그인을 성공하면 홈 화면으로 이동한다.
- 자동 로그인에 실패하면 로그인 화면으로 이동한다.

## todo
- [ ] 자동 로그인 시도
- [ ] 자동 로그인 성공하면 홈 화면으로 이동
- [ ] 자동 로그인 실패하면 로그인 화면으로 이동
