### ISSUE TITLE
썸네일 저장 API 작성하기

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#252]
## issue
[썸네일 저장 API](https://www.notion.so/jeong9216/API-cbb7fd35b86f4ed88c36558b158cc957?pvs=4)

<h3>[2] 서버리스를 통한 썸네일 생성</h3>
<ul>
<li>
<p>원본 파일을 다운샘플링해서 <code>abcd-defh/thumbnail.jpg</code>로 저장</p>
</li>
<li>
<p>사진에 대한 썸네일을 데이터베이스에 반영해주는 API</p>
<pre><code class="language-tsx">// 어드민 계정으로만 요청
// 서버리스에서 보내는 요청
POST /api/v1/thumbnails/abcd-efgh    ///api/v1/achievement/photos
Authorization: Bearer {token}
</code></pre>
<p>Photo</p>

id{uuid} | orignial_name | image_url | large_url | small_url | thumbnail_url | achievement_id
-- | -- | -- | -- | -- | -- | --
abcd-efgh | IMG01.HEIF | https://ncp/{uuid}/image.jpg | NULL | NULL | https://ncp/{uuid}/thumbnail.jpg | NULL

<pre><code class="language-tsx">204 No Content
</code></pre>
</li>
</ul>

## todo

- [ ] 관리자 권한으로 제한
- [ ] 사진의 id로 해당 사진 칼럼의 썸네일 저장
- [ ] 관련 테스트 코드
