### ISSUE TITLE
그룹 테이블을 설계한다.

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#287]
## issue
그룹 테이블을 설계한다.

## todo
- [ ] 그룹 테이블을 설계한다.
- [ ] 그룹 엔티티 코드를 작성한다.
- [ ] 그룹 도메인 코드를 작성한다.

**Comment by Dltmd202** [comment]
### [수정된 ERD](https://dbdiagram.io/d/Motimate-654b3f267d8bbd6465bc6b35)
