### ISSUE TITLE
[Feature] moti 프로젝트를 생성한다.

### ISSUE THREAD

**Issue by jeongju9216** [boostcampwm2023/iOS02-moti#3]
## issue
moti 프로젝트를 생성한다.

## todo
- [x] Xcode 프로젝트를 생성한다.
- [x] SwiftLint를 설정한다.
- [x] Xcode 팀 계정과 개발, 배포 인증서를 공유한다.
- [x] Swift Package로 클린 아키텍처 레이어를 분리한다.

**Comment by jeongju9216** [comment]
SwiftLint의 SPM이 제대로 동작하지 않아 brew install로 적용함
