### ISSUE TITLE
그룹 순서를 변경할 수 있다.

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#604]
## issue
그룹 순서를 변경할 수 있다.

## todo
- [ ] 그룹 순서를 변경할 수 있도록 유저 테이블 변경
- [ ] 그룹 순서 변경을 위한 API
- [ ] 그룹을 삭제하더라도 그룹 순서 변경 API에 문제가 없도록 수정
