### ISSUE TITLE
[Feature] 버전 수정 Api 작성하기

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#66]
## issue
버전 정보를 수정할 수 있는 API 만들기

## todo
- [ ] 수정을 위한 비즈니스 로직 생성
- [ ] 버전 정보 수정 비즈니스 로직을 위한 테스트 코드
- [ ] PUT `/operate/policy ` 작성
- [ ] PATCH `/operate/policy `작성
