### ISSUE TITLE
사용자 본인에 대한 카테고리 리스트를 반환하는 API 작성한다.

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#67]
## issue
사용자 본인에 대한 카테고리 리스트를 반환하는 API 작성하기

## todo
- [ ] 사용자 본인데 대한 카테고리 리스트를 반환하는 비즈니스 로직 작성
- [ ] 카테고리가 너무 많으면 어떻게 할지도 고민해보기
- [ ] 해당 비즈니스 로직에 대한 테스트 코드 작성
- [ ] GET `/category` 작성
