### ISSUE TITLE
[Feature] 카테고리 추가 API 작성하기

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#68]
## issue
카테고리 추가 API 작성하기

## todo
- [ ] 카테고리 추가를 위한 비즈니스 로직 생성하기
- [ ] 해당 비스니스 로직 테스트 코드 작성하기
- [ ] POST `/category` 작성하기
