### ISSUE TITLE
[Feature] 홈 화면의 커스텀 탭바를 구현한다.

### ISSUE THREAD

**Issue by jeongju9216** [boostcampwm2023/iOS02-moti#70]
## issue
 홈 화면의 커스텀 탭바를 구현한다.

## todo
- [x] 커스텀 탭바 구현
- [x] 개인 탭을 누르면 개인 화면으로 이동
- [x] 그룹 탭을 누르면 그룹 화면으로 이동
- [x] 촬영 버튼을 누르면 촬영 화면으로 이동
- [x] 촬영 버튼의 가운데 원이 touchDown일 때 작아지도록 구현
